import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/shared/Navbar'
import { CartProvider } from '@/components/cart/context'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by Muhammad Jan',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en">
      <CartProvider>
      <body>
        <Navbar />
        {children}
        </body>
    </CartProvider>
      </html>
  )
}