import { type Metadata } from 'next'

import '../globals.css'


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='h-screen flex justify-center items-center'>
        {children}
    </div>
  )
}